### добавить предмет в кладовку

POST http://localhost:8080/api/items
content-type: application/json

{
    "type": "mace",
    "minDmg": 3,
    "maxDmg": 25
}

### добавить коллекцию предметов

POST http://localhost:8080/api/items/collections
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1OThiNTk4NTFlM2M1NjEzNDA2ZjFkYTgiLCJ1c2VyIjoiZW5vdCIsImVtYWlsIjoiZW5vdE1haWwiLCJpYXQiOjE1MDIzNDkzOTF9.cWvnLaKZDeYg0p0k_kzx_7Ilp_uaMqgGI7TtmceKNF8
content-type: application/json

[
    {
        "type": "mace",
        "minDmg": 3,
        "maxDmg": 25,
        "critDmg": 0,
        "critChance": 0
    },
    {
        "type": "axe",
        "minDmg": 1,
        "maxDmg": 2,
        "critDmg": 0,
        "critChance": 0
    }
]

### получить предмет из кладовки

GET http://localhost:8080/api/items/590a2f2868789115a8c9cbd8

### получить все предметы из кладовки

GET http://localhost:8080/api/items/

### удалить предмет из кладовки

DELETE http://localhost:8080/api/items/590a2f2868789115a8c9cbd8

### удалить все предметы из кладовки

DELETE http://localhost:8080/api/items/

### добавить персонажа в кладовку

POST http://localhost:8080/api/chars
content-type: application/json

{
    "atkSpd": 54,
    "dmg": 3,
    "critChance": 5,
    "critDmg": 6
}

### добавить пользователя

POST http://localhost:8080/api/users
content-type: application/json

{
    "email": "enotMail",
    "name": "enot",
    "password": "enotPass"
}

### получить токен

POST http://localhost:8080/api/tokens
content-type: application/json

{
    "email": "enotMail",
    "password": "enotPass"
}

### hui

GET http://localhost:8080/api/test
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1OThiNTk4NTFlM2M1NjEzNDA2ZjFkYTgiLCJ1c2VyIjoiZW5vdCIsImVtYWlsIjoiZW5vdE1haWwiLCJpYXQiOjE1MDIzNDkzOTF9.cWvnLaKZDeYg0p0k_kzx_7Ilp_uaMqgGI7TtmceKNF8

