sudo: required
language: node_js
git:
  depth: 1
services:
- docker
before_install:
- npm install
- npm run lint
install:
- docker-compose up dev mongo-server selenium
- docker-compose exec dev npm run deps
- docker-compose exec dev npm start
script:
- docker-compose exec dev npm test
branches:
  only:
  - master