version: '2'

services:
  dev:
    build: .
    volumes:
      - .:/src
      - /src/logs
    ports:
      - 8080:8080 #domain port
  mongo-server:
    image: mongo
  selenium:
    image: selenium/standalone-chrome
    expose:
     - 4444
    ports:
     - 5900:5900
