version: '2'

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: kladovka/frontend
    volumes:
     - .:/src
     - /src/frontend/node_modules
     - /src/domain/node_modules
    command: ["npm", "run", "start"]
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: kladovka/backend
    volumes:
     - .:/src
     - /src/backend/node_modules
     - /src/domain/node_modules
    entrypoint: ["bash", "../wait-for-it.sh", "-t", "30", "mongo-server:27017", "--"]
    command: ["npm", "run", "start"]
    ports:
     - 8080:8080 # main port
    depends_on:
     - mongo-server
  mongo-server:
    image: mongo