version: '2'

services:
  dev:
    build: .
    image: kladovka/dev
    volumes:
      - .:/src
      - /src/logs
    ports:
      - 8080:8080 #domain port
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: kladovka/prod
    ports:
      - 8080:8080 #domain port
    depends_on:
      - mongo-server
    command: ["npm", "run","start:prod"]
  mongo-server:
    image: mongo
  selenium:
    image: selenium/standalone-chrome
    expose:
     - 4444
    ports:
     - 5900:5900
