### добавить предмет в кладовку

POST http://localhost:8080/api/items
content-type: application/json

{
    "type": "mace",
    "dps": 333,
    "hui": 25
}

### получить все предметы из кладовки

GET http://localhost:8080/api/items/

### удалить предмет из кладовки

DELETE http://localhost:8080/api/items/59076f92363279042041e7e0

### удалить все предметы из кладовки

DELETE http://localhost:8080/api/items/
